# Paths
routes_out: solution_routes.json
summary_out: solution_summary.csv
 
# Case
tsp: false
tsp_nodes: "Problems/TSP/eil76.tsp"
tsp_depot_id: 1 
tsp_vehicles: "Problems/vrp_vehicles.csv"

# GIB
gib: true
gib_nodes: "Problems/GIB.csv"
gib_depot_id: 0
gib_vehicles: "Problems/GIB_vehicles.csv"

# RL PARAMETERS
nn_path: "results/a280_train/ntnsga2_learn_run1/epoch_99/secondNN.pt" # path to load/save the SecondNN checkpoint

# Training loop
epochs: 100 # outer epochs in your run() loop
batch_size: 4 # number of episodes per policy update

# REINFORCE update knobs
entropy_coef: 0.0001
std_reg_coef: 0.0 
std_target: 0.25
adv_clip: 5.0

# Output folder for all CSV/JSON results
output_dir: results/testing

logger: INFO # TRACE | INFO

# Algorithm parameters
time_limit: 2.8
algo_params:
  nsga2:
    population_size: 50
    crossover_rate: 0.7
    mutation_rate: 0.1
  ga:
    population_size: 50
    crossover_rate: 0.7
    mutation_rate: 0.1
  aco:
    number_of_ants: 50
    pheromone_exponent: 1.0
    heuristic_exponent: 5.0
    evaporation_rate: 0.2
  pso:
    population_size: 200
    inertia_weight: 0.5
    cognitive_coefficient: 1.6
    social_coefficient: 1.6
    
  GA_Goldberg:
    population_size: 100
    crossover_rate: 0.9
    mutation_rate: 0.05

  PSO_Kennedy:
    population_size: 60
    cognitive_coeff: 2.2
    social_coeff: 2.2

  ACO_Stutzle:
    number_of_ants: 160
    pheromone_exponent: 1.0
    heuristic_exponent: 4.0
    evaporation_rate: 0.2
    pheromone_constant: 1.0
    p_best: 0.05
    tau_max: 1.0
    tau_min: 0.1

  NSGA2_Deb:
    population_size: 100
    crossover_rate: 0.7
    mutation_rate: 0.3
    eta_c: 6.0
    eta_m: 6.0

  
